import type { ShowState } from "./showState";

export const defaultShowState: ShowState = {
  live: true,
  voice: {
    origin: "https://voice.anky.app",
    connected: false,
    mask: null,
  },
  caption: {
    speaker: "mask",
    text: "the mask is on. ask me what your century has done with thought.",
  },
  clocks: {
    left: {
      label: "Chile",
      timeZone: "America/Santiago",
    },
    right: {
      label: "New York",
      timeZone: "America/New_York",
    },
  },
  host: {
    name: "JP",
    source: "obs",
  },
  center: {
    kind: "image",
    src: "/assets/black-hole.svg",
    caption: "generated by @banksy",
  },
  guest: {
    kind: "image",
    src: "/assets/anky-einstein.svg",
    title: "Anky as Einstein",
  },
  lowerThird: {
    showLogo: true,
    headline: {
      before: "What is time",
      highlight: "doing to us?",
      after: "",
    },
    quote: {
      speaker: "Einstein",
      text: "Time is an illusion that collapses into now",
    },
    cta: "DOWNLOAD ANKY: WRITE 8 MINUTES",
  },
  ticker: [
    { icon: "/tokens/ansem.svg", symbol: "$ANSEM" },
    { icon: "/tokens/dickbutt.svg", symbol: "$DICKBUTT" },
    { icon: "/tokens/world.svg", symbol: "$WORLD" },
    { icon: "/tokens/anky.svg", symbol: "$ANKY" },
    { icon: "/tokens/zayed.svg", symbol: "$ZAYED" },
  ],
};
